# Generated by Django 4.1.7 on 2023-04-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (3, 'Medium'), (3, 'Low'), (4, 'No Priority')]),
        ),
    ]
