# Generated by Django 4.1.7 on 2023-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
